server:
  port: 8080
  tomcat:
    connection-timeout: 60000
    keep-alive-timeout: 60000


spring:
  datasource:
    url: jdbc:mysql://60.205.0.18:3310/EPAMS?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    #    serverTimezone记得从UTC修改为GMT%2B8 北京时间东八区 不然会差8小时，同时不能改成CCT，会连不上数据库
    username: root
    password: neu6053
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # 进行数据库连接池的配置    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置 不可放到druid子目录下，会导致druidconfig配置文件无法识别到此处配置，直接放到datasource下即可
    min-idle: 5                                   # 数据库连接池的最小维持连接数
    initial-size: 5                               # 初始化提供的连接数
    max-total: 5                                  # 最大的连接数
    max-wait-millis: 200                          # 等待连接获取的最大超时时间
    time-between-eviction-runs-millis: 60000      # 连接池的清理线程运行时间间隔
    min-evictable-idle-time-millis: 300000        # 连接池的最小空闲时间
    validation-query: SELECT 1 FROM DUAL          # 验证连接是否有效的SQL语句
    test-while-idle: true                         # 是否在空闲时检查连接的有效性
    test-on-borrow: false                         # 是否在获取连接时检查连接的有效性
    test-on-return: false                         # 是否在归还连接时检查连接的有效性
    pool-prepared-statements: true                # 是否缓存预编译语句
    max-open-prepared-statements: 20              # 缓存预编译语句的最大数量
    filters: stat,wall,log4j2                     # 配置监控统计拦截的filters



    druid:
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

  redis:
    port: 6379
    host: 60.205.0.18
    password: 123456
    database: 0
    timeout: 5000 #超时时间

    lettuce:
      pool:
        MaxTotal: 50 #最大连接数
        minIdle: 1
        maxWaitMillis: 5000
        maxIdle: 5
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
      cluster:   # 解决redis 240秒超时问题
        refresh:
          adaptive: true
          period: 20

  servlet:
    multipart:
      enabled: true
      # 文件上传的最大值
      max-file-size: 512MB
      # 文件请求的最大值
      max-request-size: 512MB


    #配置mybatis-plus
mybatis-plus:
  typeAliasesPackage: com.neusoft.neu6053.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志

logging:
  config: classpath:log4j2.xml

log4j:
  logger:
    org.quartz: INFO

#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 文件上传位置
fileLocation: static/files

