server:
  port: 8080
  tomcat:
    connection-timeout: 60000
    keep-alive-timeout: 60000




spring:
  datasource:
    url: jdbc:mysql://60.205.0.18:3310/EPAMS?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: neu6053
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    druid:
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

  redis:
    port: 6379
    host: 60.205.0.18
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 0
        max-wait: 60000
    timeout: 1000

  servlet:
    multipart:
      enabled: true
      # 文件上传的最大值
      max-file-size: 512MB
      # 文件请求的最大值
      max-request-size: 512MB

    #配置mybatis-plus
mybatis-plus:
  typeAliasesPackage: com.neusoft.neu6053.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志

logging:
  config: classpath:log4j2.xml

log4j:
  logger:
    org.quartz: INFO

#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 文件上传位置
fileLocation: static/files

